# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180304_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.CharField(default=120, max_length=1200),
            preserve_default=False,
        ),
    ]
