# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(),
        ),
    ]
